/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/flights/live': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Борта для отрисовки маркеров на карте
         * @description Основной запрос карты. Возвращает **плоский массив** позиций, без конверта и без метаданных о свежести — за свежестью идти в `GET /pipeline-status`.
         *
         *     Возвращаются **все** борта, попавшие в область, — искусственного потолка на размер ответа нет. Без bbox на мировом зуме это порядка 10–15 тысяч объектов, и прореживать их, если нужно, клиент решает сам.
         *
         *     Единственная отсечка — по свежести: борт, о котором не было позиции дольше `YT_MAX_POSITION_AGE_SECONDS` (по умолчанию 300 с), из выдачи пропадает. Она обязательна, потому что `positions_current` хранит последнюю позицию каждого `icao24` вечно, и без неё на карте навсегда зависают борта, севшие часы назад.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Западная граница видимой области карты.
                     *
                     *     Параметры `lonMin`/`latMin`/`lonMax`/`latMax` задаются **только все четыре вместе**. Если задан не весь набор, фильтр молча игнорируется и вернётся весь мир — ошибки при этом не будет, но ответ окажется на порядок тяжелее ожидаемого.
                     *
                     *     Значение вне карты (`NaN`, `Infinity`, широта больше 90°) — это 400. А вот перевёрнутая рамка (`lonMin > lonMax` или `latMin > latMax`) вернёт пустую выдачу, а не ошибку. Переход через антимеридиан (±180°) не поддержан — такой bbox тоже даст пусто.
                     *
                     *     Один и тот же набор имён используют все ручки с картой; порядок «долгота, потом широта» взят из продуктового контракта `docs/openapi.yaml`, из которого фронтенд генерит типы.
                     */
                    lonMin?: components['parameters']['LonMin'];
                    /** @description Южная граница видимой области карты */
                    latMin?: components['parameters']['LatMin'];
                    /** @description Восточная граница видимой области карты */
                    lonMax?: components['parameters']['LonMax'];
                    /** @description Северная граница видимой области карты */
                    latMax?: components['parameters']['LatMax'];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Массив позиций. Пустой массив — валидный ответ и **не** признак ошибки: так же выглядит и пустой участок карты, и остановленный пайплайн. Различить их можно только через `GET /pipeline-status`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Flight'][];
                    };
                };
                /** @description Параметр не разобрался как число либо задан вне карты (`lonMin=NaN`, `latMax=200`). Осмысленные, но абсурдные значения (перевёрнутая рамка, неполный набор координат) под этот случай **не** подпадают — они обрабатываются молча. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/flights/{icao24}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Последняя известная позиция борта
         * @description Карточка борта по клику на карте. Тело ответа — тот же объект, что и элемент массива в `GET /flights/live`.
         *
         *     Трек сюда **не входит**, за ним нужен отдельный запрос к `GET /flights/{icao24}/track`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ICAO24-адрес борта: ровно 6 hex-символов. Регистр не важен, сервер приводит значение к нижнему. Всё, что не подходит под формат, — это 400 на любой ручке, а не «борт не найден». */
                    icao24: components['parameters']['Icao24'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Flight'];
                    };
                };
                /** @description `icao24` не прошёл проверку формата — это не 6 hex-символов. Поле `message` заполнено по-русски и пригодно для показа пользователю. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                /**
                 * @description Формат кода верный, но борта нет в `positions_current` — он не наблюдался дольше окна свежести.
                 *
                 *     Поле `message` заполнено по-русски и пригодно для показа пользователю.
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/flights/{icao24}/track': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Трек борта из накопленной истории
         * @description Точки строятся по `positions_history` и приходят **уже в хронологическом порядке** — сортировать на клиенте не нужно.
         *
         *     Плотность точек — одна на опрос пайплайна, то есть примерно раз в 15 секунд (около 240 точек за час). В паузах пайплайна в треке будут разрывы, поэтому соединять прямой линией далеко разнесённые по времени точки не стоит.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Глубина окна назад от текущего момента, в секундах. Значение вне диапазона 1…86400 — это 400, а не молча усечённое окно: раньше отрицательное `sinceSeconds` снимало отсечку по времени и запрос выгребал историю борта целиком. */
                    sinceSeconds?: number;
                };
                header?: never;
                path: {
                    /** @description ICAO24-адрес борта: ровно 6 hex-символов. Регистр не важен, сервер приводит значение к нижнему. Всё, что не подходит под формат, — это 400 на любой ручке, а не «борт не найден». */
                    icao24: components['parameters']['Icao24'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Массив точек трека. Пустой массив означает, что за окно точек не накопилось: в отличие от карточки борта, отсутствие истории у существующего борта — это не 404. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['TrackPoint'][];
                    };
                };
                /** @description `icao24` не прошёл проверку формата либо `sinceSeconds` вне диапазона 1…86400. Поле `message` заполнено по-русски. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/airports': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список аэропортов из справочника OurAirports
         * @description Справочник `ref_airports` (OurAirports) с фильтрацией, сортировкой и пагинацией — FR12. Загруженности, числа рейсов и индекса трафика здесь **нет**: считать их не из чего, в пайплайне нет ни одной таблицы рейсов.
         *
         *     **Отдаются не все строки справочника.** В OurAirports 86 тысяч записей, из которых 23 тысячи вертодромов, 13 тысяч закрытых площадок, полторы тысячи гидроаэродромов и воздухоплавательных площадок. Наружу уходят только `large_airport`, `medium_airport` и `small_airport` — около 48 тысяч. Отключить этот фильтр параметром нельзя: вертодром на карте рейсов не принимает, а список аэропортов он засоряет. Из-за него же `total` меньше `row_count` таблицы.
         *
         *     **Первый запрос после старта сервиса занимает десятки секунд.** `ref_airports` — статическая таблица, `select_rows` по ней не работает («Table ... is not dynamic»), поэтому она читается целиком через `read_table`: ~20 МБ и порядка 40 секунд. Снапшот кладётся в память и живёт `YT_REF_AIRPORTS_CACHE_TTL_SECONDS` (сутки по умолчанию), так что последующие ответы — миллисекунды. Обратная сторона: перезалив справочника сервис заметит только после истечения TTL или рестарта.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Подстрока без учёта регистра. Ищется по тем же полям, которые видны в ответе: `name`, `city`, `icao`, `iata`. Совпадение — именно подстрока, а не префикс: `sheremet` найдёт «Sheremetyevo International Airport».
                     *
                     *     Подстановочных символов нет. Значение сравнивается в памяти и в запрос к YTsaurus не попадает, поэтому кавычка и процент — обычные символы: они просто ничему не соответствуют и дают пустой список, а не ошибку. Длиннее 100 символов значение обрезается.
                     *
                     *     Поиск по коду аэропорта работает не для всех строк: `icao` — это `icao_code`, а если он пуст (88% записей OurAirports), то `ident`. У 785 записей заполнены оба и они различаются — такую строку найдёт `icao_code`, но не `ident`.
                     */
                    search?: string;
                    /** @description Точное совпадение с `iso_country` — двухбуквенный код ISO 3166-1 alpha-2, регистр не важен. Не подстрока: `RU` не найдёт `RUS`. Неизвестный код — пустой список и `total: 0`, а не 400. */
                    country?: string;
                    /**
                     * @description Единственное поддержанное значение — `name` (по названию, без учёта регистра, ничьи разрешаются по `icao`). Значения `trafficIndex` и `totalFlights` из `docs/openapi.yaml` не реализованы: этих метрик в ответе нет.
                     *
                     *     Без параметра порядок — как в таблице, то есть по `ident` по возрастанию; он детерминирован, поэтому пагинация без сортировки тоже не перемешивает страницы. Незнакомое значение молча игнорируется и даёт тот же табличный порядок.
                     */
                    sortBy?: 'name';
                    /** @description Номер страницы, начиная с 1. Значения меньше 1 подтягиваются к 1, а не отвергаются. Страница за концом выборки — пустой `items` при неизменном `total` и с тем самым `page`, который запросили. */
                    page?: number;
                    /** @description Размер страницы. Значение зажимается в диапазон 1…500, то есть `pageSize=100000` вернёт 500 записей и `pageSize: 500` в ответе — запросить весь справочник одним ответом нельзя. */
                    pageSize?: number;
                    /**
                     * @description Западная граница видимой области карты.
                     *
                     *     Параметры `lonMin`/`latMin`/`lonMax`/`latMax` задаются **только все четыре вместе**. Если задан не весь набор, фильтр молча игнорируется и вернётся весь мир — ошибки при этом не будет, но ответ окажется на порядок тяжелее ожидаемого.
                     *
                     *     Значение вне карты (`NaN`, `Infinity`, широта больше 90°) — это 400. А вот перевёрнутая рамка (`lonMin > lonMax` или `latMin > latMax`) вернёт пустую выдачу, а не ошибку. Переход через антимеридиан (±180°) не поддержан — такой bbox тоже даст пусто.
                     *
                     *     Один и тот же набор имён используют все ручки с картой; порядок «долгота, потом широта» взят из продуктового контракта `docs/openapi.yaml`, из которого фронтенд генерит типы.
                     */
                    lonMin?: components['parameters']['LonMin'];
                    /** @description Южная граница видимой области карты */
                    latMin?: components['parameters']['LatMin'];
                    /** @description Восточная граница видимой области карты */
                    lonMax?: components['parameters']['LonMax'];
                    /** @description Северная граница видимой области карты */
                    latMax?: components['parameters']['LatMax'];
                    /** @description Картовый режим: сколько аэропортов вернуть одним ответом. Заданный `limit` **отменяет** табличную пагинацию — `page` и `pageSize` в запросе игнорируются, а в ответе приходят `page: 1` и `pageSize`, равный фактическому лимиту. `total` при этом остаётся полным размером выборки после фильтров, так что по нему видно, сколько объектов не поместилось. Значение зажимается в диапазон 1…10000. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница справочника. Пустой `items` — валидный ответ: так выглядят и слишком узкий фильтр, и страница за концом выборки. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportsListResponse'];
                    };
                };
                /** @description Параметр не разобрался как число (`page=abc`, `latMin=север`) либо координата задана вне карты (`lonMin=NaN`, `latMax=200`). Осмысленные, но абсурдные значения (`page=0`, `pageSize=100000`, перевёрнутый bbox) под этот случай **не** подпадают — они обрабатываются молча. У координат `message` русский, у ошибок разбора — техническое пояснение от Spring, по-английски. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                /** @description YTsaurus недоступен, вернул ошибку или таблицы `ref_airports` нет по настроенному пути — и при этом справочник ещё ни разу не читался. Если снапшот уже есть в памяти, ручка продолжает отвечать им, даже когда TTL истёк, а YTsaurus недоступен. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/pipeline-status': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние поставщика позиций
         * @description Отвечает на вопрос «почему на карте пусто». Без этого эндпоинта отличить остановленный пайплайн от честно пустого участка карты невозможно — оба случая выглядят как `200 []`.
         *
         *     Отвечает «едут ли данные вообще», но не «почему встали»: источник — таблица watermark'ов `pipeline_job_state`, причин остановки в ней нет.
         *
         *     Достаточно поллить раз в 30 секунд, отдельно от позиций.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Текущее состояние. Отвечает всегда, даже если пайплайн ни разу не запускался — тогда `status: unknown` и `stale: true`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PipelineStatus'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/dashboard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Снапшот статистики для дашборда
         * @description Единственный запрос дашборда: отдаёт последний посчитанный снапшот целиком — счётчики, распределение по фазам, топ аэропортов, топ маршрутов, разбивку по производителям и тренд.
         *
         *     Параметров нет намеренно. Клиент не может попросить период: в YT лежит ровно один снапшот, и `computedAt` в ответе — единственное, что о его актуальности известно. Насколько снапшот свежий, клиент решает сам, сравнив `computedAt` с текущим временем; по NFR2 джоба обязана пересчитывать агрегаты не реже раза в час.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Снапшот целиком. Нулевые счётчики — валидный ответ: так выглядит и пересчёт по пустому окну, и остановленный ингест. Отличить одно от другого по этой ручке нельзя. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['DashboardResponse'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/airports': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Рейсы аэропортов за сутки
         * @description Вылеты и прилёты каждого аэропорта, о котором в `airport_events` есть хотя бы одно событие, отсортированные по сумме рейсов. Это то самое `totalFlights24h`, которого нет в справочнике `positions-service`: рейсы считаются не по `ref_airports`, а по размеченным событиям.
         *
         *     Окно — **последние сутки имеющихся данных**, а не последние сутки по часам сервиса: пайплайн встаёт, и по календарным суткам ответ был бы пустым при живых событиях вчерашнего батча. Фактические границы всегда приходят в `from`/`to`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Аэропорты с рейсами за окно; пустой список — валидный ответ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportsTrafficResponse'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/hourly-traffic': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Часовой профиль вылетов и прилётов
         * @description Тайм-серия по `airport_events` с шагом в час. В отличие от `trafficTrend` из дашборда это профиль **по истории рейсов**, а не по моментам, когда отработала джоба, поэтому шаг ровный и по нему видно суточную волну.
         *
         *     Часы без событий приходят явными нулями: без них на графике рвётся ось времени, а провал в данных выглядит как отсутствие точек.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Ограничить профиль одним аэропортом. Код проверяется форматом — буквы, цифры и дефис, 2–8 символов; всё остальное 400 */
                    icao?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Непрерывный ряд часов внутри окна */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['HourlyTrafficResponse'];
                    };
                };
                /** @description Код аэропорта не подошёл под формат */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/emergencies': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Борта с сигналом бедствия
         * @description Список бортов с кодом 7500 (захват судна) или 7700 (аварийная ситуация) — то же, что `emergencyCount` в дашборде, но поимённо и с координатами, чтобы их можно было показать на карте.
         *
         *     Борта берутся из текущего снапшота `positions_current`, а не из агрегатов, поэтому актуальность отвечает `asOf`, а не `computedAt`. Борт, о котором не было позиции дольше `STATS_MAX_POSITION_AGE_SECONDS` (по умолчанию 300 с), из выдачи пропадает: `positions_current` хранит последнюю позицию вечно, и без отсечки вчерашний сигнал бедствия навсегда остался бы «текущим».
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пустой список — штатный и самый частый ответ: в небе может не быть ни одного сигнала бедствия. Он же приходит, когда ингест стоит и все позиции протухли */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['EmergenciesResponse'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/airports/{icao}/flights': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лог вылетов и прилётов аэропорта
         * @description Уже наблюдённые рейсы, а не борд предстоящих: каждая запись — момент, когда пайплайн увидел борт у полосы, из `airport_events`.
         *
         *     Позывной берётся из `flights_segments` по `flight_id`, авиакомпания — из `ref_aircraft` по `icao24`. Обоих может не быть: справочник ВС знает эксплуатанта примерно у трети бортов лога, и борт без него из выдачи **не** пропадает (FR4) — приходит `null`.
         *
         *     `otherAirport` — противоположный конец маршрута, тоже оценка по треку, и он известен примерно у каждого десятого события. Продуктовый контракт описывает его как `EstimatedAirportRef` с `asOf` и `candidatesCount`; этих полей в YTsaurus нет, поэтому вместо них рядом с записью идут честные `confidence` и `distanceKm` из разметки.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр направления. `all` и отсутствие параметра равнозначны; всё, кроме `arrival`, `departure` и `all`, — это 400 */
                    direction?: 'arrival' | 'departure' | 'all';
                };
                header?: never;
                path: {
                    /** @description Код аэропорта из `ref_airports`: буквы, цифры и дефис, 2–8 символов. Регистр не важен, сервер приводит значение к верхнему. Всё, что не подходит под формат, — это 400, а не «аэропорт не найден» */
                    icao: components['parameters']['AirportIcao'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Записи за то же окно, что у `/stats/airports`, свежие первыми. Пустой список означает, что за сутки данных аэропорт не отметился */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportFlightsResponse'];
                    };
                };
                /** @description Код аэропорта или направление не подошли под формат */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                /** @description Такого кода нет в `ref_airports` */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/airports/{icao}/stats': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Рейсы одного аэропорта за сутки
         * @description То же окно и тот же источник, что у `/stats/airports`, но по одному аэропорту — для карточки аэропорта.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Код аэропорта из `ref_airports`: буквы, цифры и дефис, 2–8 символов. Регистр не важен, сервер приводит значение к верхнему. Всё, что не подходит под формат, — это 400, а не «аэропорт не найден» */
                    icao: components['parameters']['AirportIcao'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Аэропорт есть в справочнике. Нули в счётчиках означают, что за окно по нему не было событий, — это не ошибка */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportStatsResponse'];
                    };
                };
                /** @description Код аэропорта не подошёл под формат */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                /** @description Такого кода нет в `ref_airports`. Пока справочник не прочитан, отличить опечатку от живого аэропорта нельзя, и сервис отвечает статистикой, а не 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ApiError'];
                    };
                };
                500: components['responses']['InternalError'];
                503: components['responses']['SourceUnavailable'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Позиция борта из `positions_current`, обогащённая справочником ВС по `icao24`.
         *
         *     Все поля всегда присутствуют в JSON; необязательность выражена через `nullable`, а не через отсутствие ключа.
         *
         *     Строка, в которой нет `icao24`, `timePosition`, `lat` или `lon`, в выдачу не попадает вовсе: подставить туда ноль значило бы показать борт в Гвинейском заливе. Поэтому бортов в ответе может оказаться меньше, чем строк записал пайплайн, — расхождение видно в логе сервиса. На `GET /flights/{icao24}` такая строка даёт 503, а не 404: борт существует, негодны данные о нём.
         */
        Flight: {
            /**
             * @description ICAO24-адрес, 6 hex-символов в нижнем регистре. Ключ борта
             * @example 01023b
             */
            icao24: string;
            /**
             * @description Позывной, уже обрезанный от пробелов
             * @example MSC2932
             */
            callsign: string | null;
            /**
             * @description Страна регистрации борта
             * @example Egypt
             */
            originCountry: string | null;
            /**
             * Format: int64
             * @description Момент фиксации позиции, unix seconds
             * @example 1786841273
             */
            timePosition: number;
            /**
             * Format: double
             * @description Широта WGS-84, градусы
             * @example 45.41
             */
            lat: number;
            /**
             * Format: double
             * @description Долгота WGS-84, градусы
             * @example 20
             */
            lon: number;
            /**
             * Format: double
             * @description Барометрическая высота в **метрах**
             * @example 10957.5
             */
            baroAltitude: number | null;
            /** @description Борт находится на земле */
            onGround: boolean;
            /**
             * Format: double
             * @description Путевая скорость в **м/с**
             * @example 229.9
             */
            velocity: number | null;
            /**
             * Format: double
             * @description Курс в градусах от севера по часовой стрелке. Задаёт поворот иконки борта на карте
             * @example 324.75
             */
            trueTrack: number | null;
            /**
             * @description Производитель из справочника ВС. Имя поля в одно слово и в нижнем регистре — так колонка называется в схеме YT
             * @example Airbus Industrie
             */
            manufacturername: string | null;
            /**
             * @description Модель ВС из справочника
             * @example A320-251N
             */
            model: string | null;
            /**
             * @description Авиакомпания-эксплуатант. Борт, которого нет в справочнике ВС, всё равно возвращается (FR4) — тогда `manufacturername`, `model` и `operator` равны `null`
             * @example Air Cairo
             */
            operator: string | null;
        };
        /** @description Одна точка трека борта из `positions_history` */
        TrackPoint: {
            /**
             * Format: int64
             * @description Момент фиксации позиции, unix seconds
             */
            timePosition: number;
            /**
             * Format: double
             * @description Широта WGS-84
             */
            lat: number;
            /**
             * Format: double
             * @description Долгота WGS-84
             */
            lon: number;
            /**
             * Format: double
             * @description Барометрическая высота в метрах, позволяет красить трек по высоте
             */
            baroAltitude: number | null;
        };
        /** @description Страница справочника аэропортов. Конверт, в отличие от `/flights/live`, нужен: без `total` клиент не может нарисовать пагинацию. */
        AirportsListResponse: {
            /**
             * Format: int64
             * @description Момент последней записи таблицы `ref_airports` (unix seconds) — `modification_time` узла в Кипарисе, а не время ответа сервиса. Справочник статический и сам по себе не пересчитывается, так что это единственная осмысленная отметка свежести: она показывает, когда пайплайн залил справочник, и не меняется от запроса к запросу. `null` — атрибут не прочитался или не разобрался; нулём это отдавать нельзя, клиент нарисовал бы 1970 год.
             * @example 1786793001
             */
            asOf: number | null;
            /** @description Аэропорты текущей страницы */
            items: components['schemas']['Airport'][];
            /**
             * @description Номер отданной страницы. Совпадает с запрошенным (после подтягивания значений < 1 к единице); в картовом режиме с `limit` всегда 1
             * @example 1
             */
            page: number;
            /**
             * @description Фактический размер страницы после зажатия в допустимый диапазон. В картовом режиме равен фактическому `limit`
             * @example 50
             */
            pageSize: number;
            /**
             * @description Сколько аэропортов подошло под фильтры — до пагинации и до `limit`, но уже **после** отсева нeаэропортовых типов
             * @example 943
             */
            total: number;
        };
        /**
         * @description Запись справочника OurAirports. Полей `totalFlights24h` и `trafficIndex` из `docs/openapi.yaml` здесь нет: рейсов по аэропортам пайплайн не считает.
         *
         *     Запись без кода, названия или координат в справочник не попадает — отрисовать и показать её всё равно нечем, а нули вместо координат увели бы аэропорт в Атлантику.
         */
        Airport: {
            /**
             * @description `icao_code` из OurAirports, а если он пуст — `ident`. Пустым не бывает, но и настоящим ICAO-кодом является не всегда: у 88% записей справочника `icao_code` не заполнен, и тогда сюда попадает локальный идентификатор вида `00AA` или `RU-0796`
             * @example UUEE
             */
            icao: string;
            /**
             * @description IATA-код. `null` у 89% записей справочника — это норма, а не сбой
             * @example SVO
             */
            iata: string | null;
            /**
             * @description Название аэропорта, как в OurAirports
             * @example Sheremetyevo International Airport
             */
            name: string;
            /**
             * @description `municipality` из OurAirports. `null` примерно у 5% записей — населённый пункт в источнике не указан
             * @example Moscow
             */
            city: string | null;
            /**
             * @description `iso_country`, код ISO 3166-1 alpha-2. По схеме таблицы поле необязательное, поэтому объявлено nullable, хотя в текущей выгрузке заполнено у всех строк
             * @example RU
             */
            country: string | null;
            position: components['schemas']['LatLon'];
        };
        /** @description Точка WGS-84 */
        LatLon: {
            /**
             * Format: double
             * @example 55.976858
             */
            lat: number;
            /**
             * Format: double
             * @example 37.41121
             */
            lon: number;
        };
        /**
         * @description Состояние пайплайна, собранное из таблицы `pipeline_job_state` — watermark'ов джобов вида `(job_name, watermark_ts, updated_at)`. Берётся джоб, отчитавшийся последним.
         *
         *     Источник знает только, докуда доехали данные, поэтому единственный содержательный сигнал здесь — `stale`. Причину остановки он не различает: паузу по лимиту кредитов OpenSky, недоступность источника и упавший джоб внешне не отличить, `resumesAt` всегда `null`. Двухступенчатый UX («обновление приостановлено до HH:MM», затем «данные устарели») на этих данных не построить — для него нужен отдельный хартбит `ingest_service`.
         */
        PipelineStatus: {
            /**
             * @description Отчитывался ли пайплайн вообще:
             *
             *     * `ok` — в таблице есть строка джоба. Означает только это: «джоб зарегистрировал своё состояние». Работает ли он **сейчас**, показывает `stale`, а не этот код.
             *
             *     * `unknown` — в `pipeline_job_state` нет ни одной строки: джобы ни разу не отчитывались либо таблицу пересоздали. Всегда приходит вместе со `stale: true`.
             * @enum {string}
             */
            status: 'ok' | 'unknown';
            /**
             * Format: int64
             * @description Watermark последнего отчитавшегося джоба, unix seconds — граница, до которой данные обработаны. Считаем свежесть именно по нему, а не по времени записи: если джоб крутится, а источник умер, время записи растёт при стоящих данных. `null` — джоб зарегистрировался, но ещё ничего не обработал
             */
            lastSuccessAt: number | null;
            /**
             * Format: int64
             * @description Момент, когда опрос возобновится, unix seconds. С текущим источником **всегда `null`**: `pipeline_job_state` про паузы ничего не знает
             */
            resumesAt: number | null;
            /** @description Данные считаются устаревшими: watermark не продвигался дольше `PIPELINE_STALE_AFTER_SECONDS` (по умолчанию 120 с). При `lastSuccessAt: null` всегда `true` */
            stale: boolean;
        };
        /**
         * @description Единое тело ошибки сервиса: его формирует `ApiExceptionHandler` для всех кодов, включая 5xx. На всех ручках `/api/**` поле `message` есть всегда. Исключение одно: `406`, когда клиент просит формат, которого у сервиса нет, — тело в этом случае пустое, потому что сериализовать его не во что.
         *
         *     У доменных ошибок (404) и у отказа YTsaurus (503) `message` написан по-русски и годится для показа пользователю. У ошибок самого Spring MVC (400 на неразобранный параметр, 405) там техническое пояснение по-английски — его лучше заменить своим текстом на клиенте.
         */
        ApiError: {
            /**
             * Format: date-time
             * @description Момент формирования ответа, ISO-8601
             * @example 2026-08-18T09:14:22.481Z
             */
            timestamp: string;
            /**
             * @description HTTP-код, дублирует статус ответа
             * @example 404
             */
            status: number;
            /**
             * @description Стандартное название HTTP-статуса
             * @example Not Found
             */
            error: string;
            /**
             * @description Причина ошибки; пустым не бывает
             * @example Позиция для борта icao24=abc123 не найдена
             */
            message: string;
        };
        /** @description Аэропорт в выдаче агрегатов. В `dashboard_*` лежит только ICAO — `iata` и `name` сервис добирает джойном с `ref_airports` (`icao_code`/`iata_code`/`name`). Если аэропорта в справочнике нет, оба поля приходят `null`, а сам аэропорт из выдачи не пропадает. */
        AirportRef: {
            /**
             * @description [Derived] dashboard_top_airports.airport_icao
             * @example EDDK
             */
            icao: string;
            /**
             * @description [OurAirports] ref_airports.iata_code
             * @example CGN
             */
            iata: string | null;
            /**
             * @description [OurAirports] ref_airports.name
             * @example Cologne Bonn Airport
             */
            name: string | null;
        };
        /** @description Строка `dashboard_totals`, одна на весь снапшот. */
        Totals: {
            /**
             * @description [OpenSky] dashboard_totals.active_flights
             * @example 917
             */
            activeFlights: number;
            /**
             * @description [OurAirports] dashboard_totals.tracked_airports
             * @example 38
             */
            trackedAirports: number;
            /**
             * Format: double
             * @description [Derived] `dashboard_totals.avg_altitude_m`, среднее по `states.baro_altitude`, метры. **Бывает `null`**: если в окне пересчёта не оказалось ни одного борта с высотой, джоба пишет `null`, а не 0 — ноль означал бы «летели на уровне моря».
             * @example 9412.5
             */
            averageAltitudeM: number | null;
            /**
             * Format: double
             * @description [Derived] `dashboard_totals.avg_velocity_mps` × 3.6 — среднее по `states.velocity`, **километры в час**. В YTsaurus поле лежит в м/с, пересчёт делает сервис.
             * @example 797
             */
            averageSpeedKmh: number | null;
        };
        /** @description Распределение бортов по фазам из `dashboard_totals`. Это **не** enum `FlightPhase` карты: в YT считается `airborne` — все борта не на земле, а не `cruising` в узком смысле. Порога «вертикальная скорость ≈ 0» джоба не применяет, поэтому `airborne` включает и `climbing`, и `descending`, и горизонтальный полёт — сумма по полям не равна `activeFlights`. */
        FlightsByPhase: {
            /** @description [OpenSky] dashboard_totals.on_ground */
            onGround: number;
            /** @description [OpenSky] dashboard_totals.airborne */
            airborne: number;
            /** @description [OpenSky] dashboard_totals.climbing, vertical_rate > 0 */
            climbing: number;
            /** @description [OpenSky] dashboard_totals.descending, vertical_rate < 0 */
            descending: number;
        };
        /** @description Строка `dashboard_top_airports`, отсортировано по `rank`. */
        BusiestAirport: {
            airport: components['schemas']['AirportRef'];
            /**
             * @description [Derived] dashboard_top_airports.departures
             * @example 12
             */
            departures: number;
            /**
             * @description [Derived] dashboard_top_airports.arrivals
             * @example 64
             */
            arrivals: number;
            /**
             * @description [Derived] `dashboard_top_airports.total_flights` — вылеты плюс прилёты, по нему же и отсортирована выдача.
             * @example 74
             */
            totalFlights: number;
        };
        /** @description Строка `dashboard_routes`. Пара строится по `flights_segments`, где аэропорты вылета и прилёта — **оценка** по ближайшей точке трека, поэтому в выдаче попадаются вырожденные пары вида `LIMC → LIMC`: борт взлетел и сел в одном аэропорту либо оценка не разошлась. Фильтровать их сервис не берётся — это забота джобы. */
        BusiestRoute: {
            origin: components['schemas']['AirportRef'];
            destination: components['schemas']['AirportRef'];
            /**
             * @description [Derived] dashboard_routes.flight_count
             * @example 5
             */
            flightCount: number;
        };
        /** @description Строка `dashboard_manufacturers`. */
        ManufacturerShare: {
            /**
             * @description [OpenSky Aircraft DB] `dashboard_manufacturers.manufacturer`. Борта, которых нет в справочнике, сведены в отдельную категорию `Unknown` — она обычно и самая крупная, и её стоит показывать отдельно от настоящих производителей.
             * @example Boeing
             */
            manufacturer: string;
            /**
             * @description [Derived] dashboard_manufacturers.flight_count
             * @example 232
             */
            flightCount: number;
        };
        /** @description Страна регистрации борта. Считается сервисом на лету — `group by origin_country` по `positions_current`, отдельной таблицы `dashboard_*` под этот разрез нет. Поле заполнено у всех бортов, поэтому сумма `flightCount` совпадает с числом бортов в снапшоте позиций. */
        CountryShare: {
            /**
             * @description [OpenSky] positions_current.origin_country
             * @example Germany
             */
            country: string;
            /**
             * @description [Derived] число бортов страны в текущем снапшоте
             * @example 1035
             */
            flightCount: number;
        };
        /**
         * @description Авиакомпания-эксплуатант. Тоже считается на лету — `group by operator` по `positions_current`.
         *
         *     Борта, у которых `operator` пуст, в выдачу **не попадают**: справочник OpenSky Aircraft DB покрывает лишь около шестой части бортов, и категория «Unknown» вышла бы крупнее всех настоящих авиакомпаний вместе взятых. Поэтому сумма `flightCount` заметно меньше `totals.activeFlights` — это ожидаемо, а не потеря данных.
         */
        AirlineShare: {
            /**
             * @description [OpenSky Aircraft DB] positions_current.operator
             * @example Ryanair
             */
            airline: string;
            /**
             * @description [Derived] число бортов авиакомпании в текущем снапшоте
             * @example 214
             */
            flightCount: number;
        };
        AirportTraffic: {
            airport: components['schemas']['AirportRef'];
            /**
             * @description [Derived] count(airport_events с direction=departure)
             * @example 13
             */
            departures: number;
            /**
             * @description [Derived] count(airport_events с direction=arrival)
             * @example 71
             */
            arrivals: number;
            /**
             * @description [Derived] вылеты плюс прилёты за окно
             * @example 84
             */
            totalFlights24h: number;
        };
        AirportsTrafficResponse: {
            /**
             * Format: int64
             * @description Начало окна, unix seconds
             */
            from: number;
            /**
             * Format: int64
             * @description Конец окна — время последнего события в таблице, а не текущее время сервиса
             */
            to: number;
            items: components['schemas']['AirportTraffic'][];
        };
        AirportStatsResponse: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            airport: components['schemas']['AirportRef'];
            departures: number;
            arrivals: number;
            totalFlights24h: number;
        };
        FlightLogEntry: {
            /**
             * @description [OpenSky] airport_events.icao24
             * @example 4bccad
             */
            icao24: string;
            /**
             * @description [OpenSky] flights_segments.callsign по flight_id
             * @example SXS4RX
             */
            callsign: string | null;
            /**
             * @description [OpenSky Aircraft DB] ref_aircraft.operator по icao24
             * @example SunExpress
             */
            airlineName: string | null;
            /** @enum {string} */
            direction: 'arrival' | 'departure';
            /** @description Противоположный конец маршрута по оценке разметки; известен примерно у каждого десятого события */
            otherAirport: components['schemas']['AirportRef'] | null;
            /**
             * Format: int64
             * @description [Derived] airport_events.event_ts — когда борт заметили у полосы
             * @example 1787133926
             */
            observedAt: number;
            /**
             * Format: double
             * @description [Derived] уверенность привязки события к аэропорту, 0..1. Заменяет `candidatesCount` продуктового контракта
             * @example 0.97
             */
            confidence: number;
            /**
             * Format: double
             * @description [Derived] расстояние от борта до аэропорта в момент события
             * @example 0.4
             */
            distanceKm: number;
        };
        AirportFlightsResponse: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            airport: components['schemas']['AirportRef'];
            /** @description Свежие записи первыми */
            items: components['schemas']['FlightLogEntry'][];
        };
        HourlyTrafficPoint: {
            /**
             * Format: int64
             * @description Начало часа, unix seconds
             * @example 1787130000
             */
            hour: number;
            departures: number;
            arrivals: number;
            /** @description Сумма — считает сервис, чтобы клиент не складывал сам */
            totalFlights: number;
        };
        HourlyTrafficResponse: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            /** @description Непрерывный ряд часов внутри окна, включая пустые */
            points: components['schemas']['HourlyTrafficPoint'][];
        };
        EmergencyFlight: {
            /**
             * @description [OpenSky] positions_current.icao24
             * @example a981a8
             */
            icao24: string;
            /**
             * @description [OpenSky] positions_current.callsign
             * @example N711VJ
             */
            callsign: string | null;
            /**
             * @description [OpenSky] код ответчика: 7500 или 7700
             * @example 7700
             */
            squawk: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            onGround: boolean;
            /**
             * Format: int64
             * @description Момент фиксации позиции, unix seconds
             */
            timePosition: number;
        };
        EmergenciesResponse: {
            /**
             * Format: int64
             * @description Момент запроса — борта берутся из текущего снапшота позиций
             */
            asOf: number;
            items: components['schemas']['EmergencyFlight'][];
        };
        /** @description Точка `dashboard_trend`. Шаг между точками **неравномерный**: строка пишется на каждый пересчёт, а он идёт не по расписанию — в истории встречаются и две точки подряд с разницей в пару минут, и разрыв в несколько часов. Клиент обязан рисовать тренд по фактическим `timestamp`, а не по номеру точки. */
        TrafficTrendPoint: {
            /**
             * Format: int64
             * @description [Derived] dashboard_trend.computed_at
             * @example 1787132036
             */
            timestamp: number;
            /**
             * @description [Derived] dashboard_trend.active_aircraft
             * @example 788
             */
            activeFlights: number;
        };
        DashboardResponse: {
            /**
             * Format: int64
             * @description [Derived] `dashboard_totals.computed_at` — когда джоба посчитала снапшот. Заменяет `from`/`to` продуктового контракта: окна агрегации в YT нет, есть только момент пересчёта.
             * @example 1787132036
             */
            computedAt: number;
            totals: components['schemas']['Totals'];
            flightsByPhase: components['schemas']['FlightsByPhase'];
            topBusiestAirports: components['schemas']['BusiestAirport'][];
            busiestRoutes: components['schemas']['BusiestRoute'][];
            aircraftByManufacturer: components['schemas']['ManufacturerShare'][];
            /** @description Топ-10 стран регистрации. В отличие от остальных полей считается по `positions_current` в момент запроса, а не берётся из снапшота `dashboard_*`, — то есть отражает «сейчас», а не `computedAt`. */
            topCountries: components['schemas']['CountryShare'][];
            /** @description Топ-10 авиакомпаний, считается так же — по `positions_current`. */
            topAirlines: components['schemas']['AirlineShare'][];
            /** @description Отсортирован по `timestamp` по возрастанию. */
            trafficTrend: components['schemas']['TrafficTrendPoint'][];
            /**
             * @description [OpenSky] `dashboard_totals.emergency_squawks` — борта с кодом 7500 или 7700 в окне пересчёта.
             * @example 0
             */
            emergencyCount: number;
        };
    };
    responses: {
        /**
         * @description Источник данных не ответил или ответил негодным: YTsaurus недоступен, вернул ошибку либо прислал тело, которое не разбирается как ответ. Сервис при этом исправен, поэтому повторить запрос осмысленно.
         *
         *     Сюда же попадает пустая `dashboard_totals` — джоба ещё ни разу не посчитала агрегаты. Отдавать в этом случае нули нельзя: дашборд показал бы «в небе никого» вместо «данных пока нет».
         *
         *     Поле `message` заполнено по-русски и пригодно для показа пользователю; подробности источника (trace_id, текст запроса) остаются в логе сервиса и наружу не выходят.
         */
        SourceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['ApiError'];
            };
        };
        /**
         * @description Сбой самого сервиса. Сюда же попадает запрос, который **отклонил** YTsaurus, — неверный путь таблицы, протухший токен, негодный QL: это дефект сервиса или его конфигурации, и, в отличие от 503, повтор не поможет.
         *
         *     В `message` всегда «Внутренняя ошибка сервиса»: показывать клиенту внутренности нечего, диагностика — в логе.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['ApiError'];
            };
        };
    };
    parameters: {
        /** @description ICAO24-адрес борта: ровно 6 hex-символов. Регистр не важен, сервер приводит значение к нижнему. Всё, что не подходит под формат, — это 400 на любой ручке, а не «борт не найден». */
        Icao24: string;
        /**
         * @description Западная граница видимой области карты.
         *
         *     Параметры `lonMin`/`latMin`/`lonMax`/`latMax` задаются **только все четыре вместе**. Если задан не весь набор, фильтр молча игнорируется и вернётся весь мир — ошибки при этом не будет, но ответ окажется на порядок тяжелее ожидаемого.
         *
         *     Значение вне карты (`NaN`, `Infinity`, широта больше 90°) — это 400. А вот перевёрнутая рамка (`lonMin > lonMax` или `latMin > latMax`) вернёт пустую выдачу, а не ошибку. Переход через антимеридиан (±180°) не поддержан — такой bbox тоже даст пусто.
         *
         *     Один и тот же набор имён используют все ручки с картой; порядок «долгота, потом широта» взят из продуктового контракта `docs/openapi.yaml`, из которого фронтенд генерит типы.
         */
        LonMin: number;
        /** @description Южная граница видимой области карты */
        LatMin: number;
        /** @description Восточная граница видимой области карты */
        LonMax: number;
        /** @description Северная граница видимой области карты */
        LatMax: number;
        /** @description Код аэропорта из `ref_airports`: буквы, цифры и дефис, 2–8 символов. Регистр не важен, сервер приводит значение к верхнему. Всё, что не подходит под формат, — это 400, а не «аэропорт не найден» */
        AirportIcao: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
