/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/flights/live': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список бортов для отрисовки маркеров на карте
         * @description Для получения обновлений "в реальном времени" клиент должен периодически повторять (поллинг) этот же запрос раз в N секунд; интервал ограничен квотой OpenSky (400–14400 кредитов/день).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Западная граница видимой области карты. Параметры lonMin/latMin/lonMax/latMax задаются только все вместе; если задан не весь набор — фильтр по области игнорируется. */
                    lonMin?: components['parameters']['LonMin'];
                    /** @description Южная граница видимой области карты */
                    latMin?: components['parameters']['LatMin'];
                    /** @description Восточная граница видимой области карты */
                    lonMax?: components['parameters']['LonMax'];
                    /** @description Северная граница видимой области карты */
                    latMax?: components['parameters']['LatMax'];
                    /** @description Текущий уровень зума карты */
                    zoom?: number;
                    /** @description Максимум бортов в ответе */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['LiveFlightsResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/flights/{icao24}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали самолёта по клику на карте
         * @description Ответ включает трек (path/startTime/endTime), чтобы при клике по борту не делать отдельный запрос к /flights/{icao24}/track; тот эндпоинт остаётся для точечного обновления/повторной подгрузки трека.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ICAO24-адрес */
                    icao24: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['FlightDetailsResponse'];
                    };
                };
                /** @description Борта нет в текущем снапшоте state vectors */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/airports': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список аэропортов с индексом загруженности
         * @description Индекс загруженности: во сколько раз текущий/сегодняшний трафик аэропорта отличается от его собственной исторической нормы. `search`/`country`/`sortBy`/`page`/`pageSize` — для табличного режима; `lonMin`/`latMin`/`lonMax`/`latMax`/`zoom`/`limit` — для отрисовки аэропортов на карте мира.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Поиск по названию/городу/коду */
                    search?: string;
                    /** @description Фильтр по iso_country */
                    country?: string;
                    sortBy?: 'trafficIndex' | 'name' | 'totalFlights';
                    page?: number;
                    pageSize?: number;
                    /** @description Западная граница видимой области карты. Параметры lonMin/latMin/lonMax/latMax задаются только все вместе; если задан не весь набор — фильтр по области игнорируется. */
                    lonMin?: components['parameters']['LonMin'];
                    /** @description Южная граница видимой области карты */
                    latMin?: components['parameters']['LatMin'];
                    /** @description Восточная граница видимой области карты */
                    lonMax?: components['parameters']['LonMax'];
                    /** @description Северная граница видимой области карты */
                    latMax?: components['parameters']['LatMax'];
                    /** @description Текущий уровень зума карты (0–20); используется бэкендом для адаптивной плотности/агрегации отдаваемых аэропортов при мелком zoom */
                    zoom?: number;
                    /** @description Максимум аэропортов в ответе для map-режима (независимо от page/pageSize, которые применяются в табличном режиме) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportsListResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/airports/{icao}/flights': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лог рейсов аэропорта за период (вылеты + прилёты)
         * @description Уже наблюдённых OpenSky рейсов, не борд предстоящих.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр направления */
                    direction?: 'arrival' | 'departure' | 'all';
                    /** @description Окно наблюдения, unix ts (проброс в /flights/departure) */
                    from?: number;
                    /** @description Окно наблюдения, unix ts (проброс в /flights/arrival) */
                    to?: number;
                };
                header?: never;
                path: {
                    /** @description ICAO-код аэропорта */
                    icao: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AirportFlightsResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/stats/dashboard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дашборд статистики */
        get: {
            parameters: {
                query?: {
                    /** @description unix ts, окно агрегации, по умолчанию последние 24ч доступного батча */
                    from?: number;
                    /** @description unix ts, окно агрегации, по умолчанию последние 24ч доступного батча */
                    to?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['DashboardResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        /** @description [OurAirports] */
        AirportRef: {
            /** @description [OurAirports] airports.icao_code / ident */
            icao: string;
            /** @description [OurAirports] airports.iata_code */
            iata: string | null;
            /** @description [OurAirports] airports.name */
            name: string;
        };
        EstimatedAirportRef: components['schemas']['AirportRef'] & {
            /**
             * Format: int64
             * @description unix ts батча /flights/*, из которого взята оценка
             */
            asOf: number;
            /** @description [OpenSky] departureAirportCandidatesCount / arrivalAirportCandidatesCount — чем больше, тем менее уверенная оценка */
            candidatesCount: number;
        };
        LatLon: {
            /**
             * Format: double
             * @description градусы WGS-84
             */
            lat: number;
            /** Format: double */
            lon: number;
        };
        /**
         * @description on_ground: [OpenSky] on_ground = true; climbing: [OpenSky] on_ground = false, vertical_rate > 0; descending: [OpenSky] on_ground = false, vertical_rate < 0; cruising: [OpenSky] on_ground = false, vertical_rate ≈ 0
         * @enum {string}
         */
        FlightPhase: 'on_ground' | 'climbing' | 'descending' | 'cruising';
        AircraftPosition: {
            /** @description [OpenSky] states[i][0] */
            icao24: string;
            /**
             * Format: double
             * @description [OpenSky] states[i][6]
             */
            lat: number;
            /**
             * Format: double
             * @description [OpenSky] states[i][5]
             */
            lon: number;
            /** @description [OpenSky] states[i][7] baro_altitude */
            altitudeM: number | null;
            /** @description [OpenSky] states[i][10] true_track */
            headingDeg: number | null;
            /** @description [OpenSky] states[i][9] velocity, м/с * 3.6 */
            speedKmh: number | null;
            /** @description [OpenSky] states[i][11] */
            verticalRateMs: number | null;
            /** @description [OpenSky] states[i][8] */
            onGround: boolean;
            /**
             * Format: int64
             * @description unix ts, [OpenSky] states[i][4] last_contact
             */
            timestamp: number;
        };
        LiveFlightsResponse: {
            /**
             * Format: int64
             * @description unix ts, [OpenSky] верхнеуровневое поле "time"
             */
            generatedAt: number;
            flights: {
                /**
                 * @description Обозначение один самолет (solo) или кластер самолетов (multie)
                 * @enum {string}
                 */
                type: 'solo' | 'multie';
                /** @description Количество самолетов в кластере иначе 1 */
                count: number;
                /** @description [OpenSky] */
                icao24: string;
                /** @description [OpenSky] states[i][1], trim */
                callsign: string | null;
                /** @description [OpenSky Aircraft DB] operator по icao24, если найден, иначе null */
                airlineName: string | null;
                position: components['schemas']['AircraftPosition'];
                phase: components['schemas']['FlightPhase'];
                /** @description [OpenSky] estDepartureAirport из последнего доступного батча /flights/* */
                origin: components['schemas']['EstimatedAirportRef'] | null;
                /** @description [OpenSky] estArrivalAirport, там же */
                destination: components['schemas']['EstimatedAirportRef'] | null;
                /** @description [OpenSky] squawk, если есть */
                squawk?: number | null;
            }[];
        };
        FlightTrackResponse: {
            /** @description [OpenSky] */
            icao24: string;
            /**
             * Format: int64
             * @description [OpenSky] tracks.startTime
             */
            startTime: number;
            /**
             * Format: int64
             * @description [OpenSky] tracks.endTime
             */
            endTime: number;
            path: {
                /**
                 * Format: int64
                 * @description [OpenSky] path[i][0]
                 */
                timestamp: number;
                /**
                 * Format: double
                 * @description [OpenSky] path[i][1]
                 */
                lat: number;
                /**
                 * Format: double
                 * @description [OpenSky] path[i][2]
                 */
                lon: number;
                /** @description [OpenSky] path[i][3] */
                altitudeM: number | null;
                /** @description [OpenSky] path[i][4] */
                headingDeg: number | null;
                /** @description [OpenSky] path[i][5] */
                onGround: boolean;
            }[];
        };
        AirportsListResponse: {
            /**
             * Format: int64
             * @description unix ts последнего батча, на котором посчитаны метрики
             */
            asOf: number;
            items: {
                /** @description [OurAirports] ident */
                icao: string;
                /** @description [OurAirports] */
                iata: string | null;
                /** @description [OurAirports] */
                name: string;
                /** @description [OurAirports] municipality */
                city: string | null;
                /** @description [OurAirports] iso_country */
                country: string;
                position: components['schemas']['LatLon'];
            }[];
            page: number;
            pageSize: number;
            total: number;
        };
        AirportFlightsResponse: {
            airport: components['schemas']['AirportRef'];
            items: {
                /** @description [OpenSky] */
                icao24: string;
                /** @description [OpenSky] */
                callsign: string | null;
                /** @description [OpenSky Aircraft DB] operator, если найден */
                airlineName: string | null;
                /** @enum {string} */
                direction: 'arrival' | 'departure';
                /** @description [OpenSky] противоположный конец маршрута, оценка */
                otherAirport: components['schemas']['EstimatedAirportRef'] | null;
                /**
                 * Format: int64
                 * @description [OpenSky] firstSeen (для departure) / lastSeen (для arrival)
                 */
                observedAt: number;
            }[];
        };
        FlightDetailsResponse: {
            /** @description [OpenSky] */
            icao24: string;
            /** @description [OpenSky] */
            callsign: string | null;
            /** @description [OpenSky Aircraft DB] registration */
            registration: string | null;
            /** @description [OpenSky Aircraft DB] manufacturername */
            manufacturer: string | null;
            /** @description [OpenSky Aircraft DB] model */
            model: string | null;
            /** @description [OpenSky Aircraft DB] operator */
            airlineName: string | null;
            /** @description [OpenSky] estDepartureAirport, последний доступный батч */
            origin: components['schemas']['EstimatedAirportRef'] | null;
            /** @description [OpenSky] estArrivalAirport, там же */
            destination: components['schemas']['EstimatedAirportRef'] | null;
            position: components['schemas']['AircraftPosition'];
            phase: components['schemas']['FlightPhase'];
            /** @description [Derived] great-circle(position, destination) / speedKmh; null, если destination неизвестен или борт on_ground */
            etaMinutes: number | null;
            /**
             * Format: int64
             * @description [OpenSky] tracks.startTime
             */
            startTime: number;
            /**
             * Format: int64
             * @description [OpenSky] tracks.endTime
             */
            endTime: number;
            path: {
                /**
                 * Format: int64
                 * @description [OpenSky] path[i][0]
                 */
                timestamp: number;
                /**
                 * Format: double
                 * @description [OpenSky] path[i][1]
                 */
                lat: number;
                /**
                 * Format: double
                 * @description [OpenSky] path[i][2]
                 */
                lon: number;
                /** @description [OpenSky] path[i][3] */
                altitudeM: number | null;
                /** @description [OpenSky] path[i][4] */
                headingDeg: number | null;
                /** @description [OpenSky] path[i][5] */
                onGround: boolean;
            }[];
        };
        TrafficHeatmapResponse: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            /** @enum {string} */
            resolution: 'country' | 'airport' | 'cell';
            cells: {
                /** @description [OpenSky] центр геоячейки по позициям states (resolution="cell"), либо [OurAirports] координаты аэропорта (resolution="airport"/"country") */
                center: components['schemas']['LatLon'];
                /** @description [OurAirports] название аэропорта/страны, null при resolution="cell" */
                label: string | null;
                /** @description [OpenSky]/[Derived] количество бортов в ячейке (states) либо рейсов аэропорта (/flights/*) за окно */
                flightCount: number;
            }[];
        };
        DashboardResponse: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            totals: {
                /** @description [OpenSky] count(states) с on_ground=false */
                activeFlights: number;
                /** @description [OurAirports] count(airports) */
                trackedAirports: number;
                /** @description [Derived] среднее по states.baro_altitude */
                averageAltitudeM: number;
                /** @description [Derived] среднее по states.velocity */
                averageSpeedKmh: number;
            };
            /** @description [Derived] распределение states по phase */
            flightsByPhase: {
                on_ground: number;
                climbing: number;
                descending: number;
                cruising: number;
            };
            topBusiestAirports: {
                airport: components['schemas']['AirportRef'];
                /** @description [OpenSky] count(/flights/departure + /flights/arrival) */
                totalFlights: number;
            }[];
            /** @description [Derived] тайм-серия по снапшотам, которые бэкенд обязан сам сохранять */
            trafficTrend: {
                /** Format: int64 */
                timestamp: number;
                activeFlights: number;
            }[];
            /** @description количество случаев с squawk=7700 или squawk=7500 */
            emergencyCount?: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Западная граница видимой области карты. Параметры lonMin/latMin/lonMax/latMax задаются только все вместе; если задан не весь набор — фильтр по области игнорируется. */
        LonMin: number;
        /** @description Южная граница видимой области карты */
        LatMin: number;
        /** @description Восточная граница видимой области карты */
        LonMax: number;
        /** @description Северная граница видимой области карты */
        LatMax: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
