server {
    listen 80;
    server_name _;

    include /etc/nginx/conf.d/parts/*.conf;
}
# добавить сертификат и после выпуска сертификата
# заменить ДОМЕН на реальный домен, убрать HTTP-only блок выше.
#
# server {
#     listen 80;
#     server_name ДОМЕН;
#     return 301 https://$host$request_uri;
# }
#
# server {
#     listen 443 ssl;
#     server_name ДОМЕН;
#
#     ssl_certificate /etc/letsencrypt/live/ДОМЕН/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/ДОМЕН/privkey.pem;
#
#     include /etc/nginx/conf.d/parts/*.conf;
# }
