server {
    listen 80;
    server_name skypulse.duckdns.org 158.160.229.142.nip.io;
    return 301 https://skypulse.duckdns.org$request_uri;
}

server {
    listen 443 ssl;
    server_name skypulse.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/skypulse.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/skypulse.duckdns.org/privkey.pem;

    include /etc/nginx/conf.d/parts/*.conf;
}