server {
    listen 80;
    server_name 158.160.229.142.nip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 158.160.229.142.nip.io;

    ssl_certificate     /etc/letsencrypt/live/158.160.229.142.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/158.160.229.142.nip.io/privkey.pem;

    include /etc/nginx/conf.d/parts/*.conf;
}
