location /api/positions/ {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /api/analytics/ {
    proxy_pass http://svc_analytics:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /swagger-ui.html {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /v3/api-docs {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
