location /api/flights {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /api/airports {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

# У analytics-service свои ручки под тем же префиксом (/api/airports/{icao}/stats
# и /flights) - regex-локация нужна, чтобы они не ушли в svc_positions выше.
location ~ ^/api/airports/[^/]+/(stats|flights)$ {
    proxy_pass http://svc_analytics:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /api/pipeline-status {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /api/stats {
    proxy_pass http://svc_analytics:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /swagger-ui.html {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location /v3/api-docs {
    proxy_pass http://svc_positions:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
