import type { components } from '@/shared/types/api';

type LiveFlightsResponse = components['schemas']['LiveFlightsResponse'];

const MOCK_TIMESTAMP = 1_785_578_400;

export const flightsMock = {
    generatedAt: MOCK_TIMESTAMP,
    flights: [
        {
            type: 'solo',
            count: 1,
            icao24: '4242b3',
            callsign: 'AFL100',
            airlineName: 'Aeroflot',
            position: {
                icao24: '4242b3',
                lat: 55.7558,
                lon: 37.6173,
                altitudeM: 10_668,
                headingDeg: 283,
                speedKmh: 872,
                verticalRateMs: 0,
                onGround: false,
                timestamp: MOCK_TIMESTAMP,
            },
            phase: 'cruising',
            origin: {
                icao: 'UUEE',
                iata: 'SVO',
                name: 'Sheremetyevo International Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            destination: {
                icao: 'KJFK',
                iata: 'JFK',
                name: 'John F. Kennedy International Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            squawk: 4721,
        },
        {
            type: 'solo',
            count: 1,
            icao24: '4243aa',
            callsign: 'SBI1073',
            airlineName: 'S7 Airlines',
            position: {
                icao24: '4243aa',
                lat: 56.8587,
                lon: 35.9176,
                altitudeM: 7_620,
                headingDeg: 45,
                speedKmh: 741,
                verticalRateMs: 4.1,
                onGround: false,
                timestamp: MOCK_TIMESTAMP,
            },
            phase: 'climbing',
            origin: {
                icao: 'UUDD',
                iata: 'DME',
                name: 'Domodedovo International Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            destination: {
                icao: 'ULLI',
                iata: 'LED',
                name: 'Pulkovo Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            squawk: 2154,
        },
        {
            type: 'solo',
            count: 1,
            icao24: '424500',
            callsign: 'UTR369',
            airlineName: 'UTair Aviation',
            position: {
                icao24: '424500',
                lat: 58.2,
                lon: 32.5,
                altitudeM: 10_058,
                headingDeg: 210,
                speedKmh: 806,
                verticalRateMs: 0,
                onGround: false,
                timestamp: MOCK_TIMESTAMP,
            },
            phase: 'cruising',
            origin: {
                icao: 'ULLI',
                iata: 'LED',
                name: 'Pulkovo Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            destination: {
                icao: 'UUWW',
                iata: 'VKO',
                name: 'Vnukovo International Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 2,
            },
            squawk: 6342,
        },
        {
            type: 'multie',
            count: 10,
            icao24: '424293',
            callsign: 'SDM6012',
            airlineName: 'Rossiya Airlines',
            position: {
                icao24: '424293',
                lat: 59.9343,
                lon: 30.3351,
                altitudeM: 9_754,
                headingDeg: 142,
                speedKmh: 835,
                verticalRateMs: -2.4,
                onGround: false,
                timestamp: MOCK_TIMESTAMP,
            },
            phase: 'descending',
            origin: {
                icao: 'ULLI',
                iata: 'LED',
                name: 'Pulkovo Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 1,
            },
            destination: {
                icao: 'UUEE',
                iata: 'SVO',
                name: 'Sheremetyevo International Airport',
                asOf: MOCK_TIMESTAMP,
                candidatesCount: 2,
            },
            squawk: 5173,
        },
    ],
} satisfies LiveFlightsResponse;
